spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://139.129.45.208:3306/hboa?serverTimezone=UTC
#    username: root
#    password: beiXINzhiKE
    url: jdbc:mysql://121.89.202.246:3306/sys?serverTimezone=UTC
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0

mybatis:
 mapperLocations: classpath:mapper/*.xml


data:
  solr:
    host: http://127.0.0.1:8081/solr

#logging:
#  config: classpath:log4j2.xml
